### ISSUE TITLE
NLP feedback

### ISSUE THREAD

**Issue by kjappelbaum** [whitead/dmol-book#104]
- [x] " it cannot distinguish certain classes of molecules (e.g., cisplatin vs transplatin) and according to folk lore is more difficult to train a neural network with" This is not necessarily specific to INChI. Other line notations share the issues (see "complicated bonds" chapter of the SELFIES perspective :D) 
- [x] "The focus of NLP on encoding molecules is mostly due to chemistry relying on publishers which prevent bulk access/ML on publications" Not super sure about this. Maybe worth looking at the history to see what the first use of NLP in chemistry was. I think one big motivation is that there are so many powerful things (e.g., the transformer models) on can simply plug-and-play reuse if one encodes chemistry in strings
- [x] I like that you discuss the fact that a bond is just a ["convenient fiction"](https://www.nature.com/articles/469026a). Perhaps one can also add multicenter bonds
- [x] Maybe show some of the intermediate values (example of tokens, padded ones ...) for people that just read and do not run the notebook

This seems like an awesome reference http://nlp.seas.harvard.edu/2018/04/03/attention.html

**Comment by whitead** [comment]
idempotent (?), permutation invariance is about atom ordering in molecular graph (not string), and question about bijective. Can't be injective, since strings like `[nop][nop][C]` will not be covered.

**Comment by whitead** [comment]
Addressed this feedback and my comment above to myself in #134
