### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by whitead** [whitead/dmol-book#11]

**Comment by Naereen** [comment]
Hi there,
I would honestly don't try to add dark mode to any recent websites: if users want dark mode, they should use browser-side battle-tested solutions like https://darkreader.org/

**Comment by oakif** [comment]
I agree with Dark Reader unless there's already a dark mode available in an updated version of the theme you're using. I've been using DR for a while now and it works quite well.

**Comment by whitead** [comment]
Thank you @Naereen and @oakif. I'll keep an eye out for a sphinx-book update, but that suggestion works for now.
