### ISSUE TITLE
Notation error Jackknife+ description (Sections 3.7.2, eqns 3.14-15)

### ISSUE THREAD

**Issue by jschrier** [whitead/dmol-book#110]
Possible notational "bug"/typo in Section 3.7.2, equations 3.14 & 3.15:

Looking at Figure 1 in the Jacknife+ paper (https://arxiv.org/pdf/1905.02928.pdf) it seems that these equations should be of the form

q_i = { f( **x\prime** ; X \ x_i) - R_i  }

(That is, the current equations suggest that the model f should be evaluated at **x_i** when creating the set, but one actually wants to evaluate the model at the new test point **x\prime**)

**Comment by whitead** [comment]
Thank you! Very good catch. Fixed in 9258bcb
