### ISSUE TITLE
Chapter 7.1.  Images

### ISSUE THREAD

**Issue by d3e5560** [whitead/dmol-book#141]
Images can be 2D (x N channels) or 3D (x N channels) in general.  For example, a segmented MRI image might be rendered as a 3D image with RGB + alpha channel.  There are other color spaces that might have more than 4 channels (I don't know, not an expert on that).

**Comment by whitead** [comment]
Yes, images may be represented many ways. I put the word "generally" to indicate it is not the only way to represent an image.  Fixed by 72f71993a443df40042d256c9961590d562de557
