### ISSUE TITLE
Minor code flaw

### ISSUE THREAD

**Issue by Olllom** [whitead/dmol-book#15]
First of all, thanks for this awesome resource.

In this [line (l. 615 on the source blob)](https://github.com/whitead/dmol-book/blob/0771d45a48de5197f5d18f35067273a3109f6e2a/dl/Equivariant.ipynb#L615), `z6_phi` was probably supposed to be `p`.

**Comment by whitead** [comment]
Wow @Olllom I would never have spotted that. Very nice catch. Fixed on latest commit.
