### ISSUE TITLE
Book doesn't run in Colab

### ISSUE THREAD

**Issue by javialra97** [whitead/dmol-book#153]
Dear Professor, 

I'm trying to install your book in colab but I have problem with:

 **ERROR: Failed building wheel for pygraphviz**

and when I used your recomendation of get the latest working versions of package, the link send me to a _Page not found_ in Github with this error:

**The 'whitead/dmol-book' repository doesn't contain the 'package/requirements.txt' path in 'master'.**

Can I skip this step and the next of importing dmol library?

**Comment by whitead** [comment]
Hi, thanks for letting me know. I'm in the process of trying to simplify the install procedure. You can skip the `dmol` package - it just brings in the necessary packages for the book. You just then install them as they come up as you work through the notebooks.

**Comment by javialra97** [comment]
ok, thanks!! 

I will close the issue then
