### ISSUE TITLE
Question on SO3 group from equivariant chapter

### ISSUE THREAD

**Issue by arunppsg** [whitead/dmol-book#154]
In [SO(3) group](https://dmol.pub/dl/Equivariant.html#so-3-group), should not the rotation matrix be  `$R_x(\\alpha)R_y(\\beta)R_z(\\gamma)$` rather than `$R_z(\\alpha)R_y(\\beta)R_z(\\gamma)$`?

**Comment by whitead** [comment]
Hi, it is not a mistake actually. SO(3) usually uses [Euler angles](https://en.wikipedia.org/wiki/Euler_angles) - zyz. I can add a note about this

**Comment by arunppsg** [comment]
Thanks for clarifying it, I didn't know about earlier. On a side note, thanks for these awesome notebooks. They are super useful to me.
