### ISSUE TITLE
Could not install dmol package

### ISSUE THREAD

**Issue by aroll727** [whitead/dmol-book#161]
**Code:**
`!pip install dmol-book`

**Error Message:**
`ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ngfa9f_1/pygraphviz_2b7bb4531d8c4aac8f1f3f15540b464d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ngfa9f_1/pygraphviz_2b7bb4531d8c4aac8f1f3f15540b464d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-_8qz0f10/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/pygraphviz Check the logs for full command output.`

**Code:**
`import dmol`

**Error Message:**
`ModuleNotFoundError: No module named 'dmol'`

OS: Ubuntu
Python ver: 3.7.13

**Comment by whitead** [comment]
Should be fixed by #162
