### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jasperhyp** [whitead/dmol-book#175]
https://dmol.pub/dl/data.html#input-data-equivariances

RHS in formula (9.2) should be $\mathbf{XW}+b-10|\mathbf W|$

Also, I wonder what $\mathbf W$ is like in this case.  $\hat{E}$ is a scalar and $\mathbf X$ is a matrix, so there seems to be an aggregation function put upon $\mathbf{XW}$.  Assuming $\mathbf W$ is some message passing with aggregation, claiming it to have "permutation variance" might not hold, as long as the aggregation is permutation invariant.  Would appreciate it if anyone could clarify this!

**Comment by whitead** [comment]
There were a lot of problems with that example. Thanks for pointing it out. Fixed (I think!)
