### ISSUE TITLE
Pin versions in setup

### ISSUE THREAD

**Issue by hgandhi2411** [whitead/dmol-book#183]
@SamCox822 and I have been seeing dependency conflicts when trying to build some notebooks. Especially, when trying to use Pytorch and simpletransformer libraries.

**Comment by whitead** [comment]
@hgandhi2411 can you just pin simpletransformers?

**Comment by SamCox822** [comment]
@hgandhi2411  I think this issue can be closed?

**Comment by hgandhi2411** [comment]
Sure, can be closed once #207 is approved
