### ISSUE TITLE
Broken link and jax incompatibility Apple Silicon M1(pro)

### ISSUE THREAD

**Issue by AlejandroGGlez** [whitead/dmol-book#192]
Hi, I am currently following the dmol book and I have faced some issues:

I am following along the code in a Jupyter notebook rather than in Collab. I set up a new environment in anaconda (Python 3.7) and installed the different packages by ```pip install dmol-book```.

The first issue that I have is that *jax* does not work natively in M1 processor (or at leat that is what I was able to gather), I managed to make it work by downgrading to ```jax == 0.2.10``` and ```jaxlib = 0.1.60```, however with that versions we do not have access to ```jax.example_libraries```. 

The second issue is that the link with the packages version is broken [https://github.com/whitead/dmol-book/blob/master/package/requirements.txt](url) 

(Very comprehensive book apart from those tiny issues, congrats!!)

**Comment by whitead** [comment]
Thanks for letting me know. Where did you find that link? I thought I fixed all instances of it. 

Yes, installing in the package right now on M1s is problematic. If you're able to get jax installed at that older version, just replace `example_libraries` with `experimental`

**Comment by AlejandroGGlez** [comment]
Chapter B. Introduction to ML 

[https://dmol.pub/ml/introduction.html](url)

**Comment by whitead** [comment]
Fixed links in #194, linking to https://github.com/google/jax/issues/8074 for JAX M1 problems
