### ISSUE TITLE
Data leakage upon train/test split in kernel learning chapter

### ISSUE THREAD

**Issue by kjappelbaum** [whitead/dmol-book#197]
I'm preparing a lecture and wanted to build on your kernel learning example. 

Just found a minor point here: You standardize the features on the full dataset - which, strictly speaking, is data leakage. 
Happy to make a PR to fix this (if you want to have this fixed). 

Also, what do you think of also adding an example with a Gaussian kernel (at least as exercise)? It might be useful to get an intuition for the meaning and importance of the lengthscale (can also try to draft a PR for this).

**Comment by whitead** [comment]
Fixed by #228
