### ISSUE TITLE
Issue on page /dl/gnn.html

### ISSUE THREAD

**Issue by mavaylon1** [whitead/dmol-book#205]
As per you definition of invariance, where the output doesn't change when the input changes, in section 8.3.1, there seems to be a typo. You say equivariant instead of invariant.

"Is this equation permutation equivariant? Yes, because the node index in our expression is index  which can be re-ordered without affecting the output." 

Same with the rest of the section 8.3.1

**Comment by whitead** [comment]
Thanks - getting fixed on #199
