### ISSUE TITLE
Co-lab installation: chapter 1

### ISSUE THREAD

**Issue by lilyminium** [whitead/dmol-book#29]
I did not find the package installation cell to work immediately, likely due to an update in RDKit since you wrote it. It's in section "1.3. Running This Notebook".

The first issue is that "sklearn" is installed -- I think the package to install is actually scikit-learn.

Secondly, I had significant trouble getting rdkit to work properly (version 2021.03.4), and it seems this is not [unique to me](https://stackoverflow.com/questions/65487584/how-to-import-rdkit-in-google-colab-these-days)

```
     11 
     12 from rdkit import rdBase
---> 13 from rdkit.DataStructs import cDataStructs
     14 from rdkit.DataStructs.cDataStructs import *
     15 
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/local/lib/python3.7/site-packages/rdkit/DataStructs/cDataStructs.so)
```

Pinning RDKit to an older version as suggested worked in my case. Just installing the missing packages with apt did not. I also bunched all the numeric-y libraries together in conda, as I've found it figures out dependencies better. (Pinning other packages might extend the notebook's lifespan in Google Co-lab, too.)

**Suggested solution**
```
!wget -c https://repo.continuum.io/miniconda/Miniconda3-py37_4.8.3-Linux-x86_64.sh
!chmod +x Miniconda3-py37_4.8.3-Linux-x86_64.sh
!time bash ./Miniconda3-py37_4.8.3-Linux-x86_64.sh -b -f -p /usr/local/

import sys
sys.path.append('/usr/local/lib/python3.7/site-packages/')
 
!conda install -y -c conda-forge rdkit=2020.09.2 numpy jaxlib jax pandas scikit-learn
!pip install jupyter-book matplotlib seaborn tabulate
```

**Comment by whitead** [comment]
Working through these issues, thanks! 

Someone has packaged rdkit in pip, which solves all these headaches. I've switched wholly to pip and version compatibility should be solved there. Pinning is a good idea and I use it for build environment but everything works now on Colab.

Solved by ca616ae64d382aeb00a95a4d2d3045b89b2c5c9d
