### ISSUE TITLE
Use of "language" is ambiguous

### ISSUE THREAD

**Issue by SeaQuench** [whitead/dmol-book#35]
Reading the section "Framework Choice", I find usage of the word "language" to be ambiguous. The author is using it in reference to any of several programming frameworks (or libraries); however, "language" infers a syntax and grammar and is thus more commonly shorthand for "programming language" when used for software development instructional materials - at least as published in the USA. Because the author has already selected a programming language, python, i recommend that the word "language" not also be used to describe an application programming interface or framework or library.

**Comment by whitead** [comment]
Agreed, this was a few instances I missed after revising based on #26 Fixed in 25a49bb
