### ISSUE TITLE
EMLP Imports broken

### ISSUE THREAD

**Issue by whitead** [whitead/dmol-book#37]
![image](https://user-images.githubusercontent.com/908389/129410720-1759a35b-a3e6-43d5-ad91-11b4381d69bf.png)

**Comment by mfinzi** [comment]
oh no! I'm very sorry that this has happened 😬 . I tested v1.0.1 on a couple of different machines and haven't had this issue yet. Is it possible an old emlp installation is conflicting somehow?

**Comment by mfinzi** [comment]
Curiously this appears to be a discrepancy between distribution I uploaded to pypi and the current on the repo. As a workaround, you should be able to just use `pip install git+https://github.com/mfinzi/equivariant-MLP.git` until I figure out what has gone wrong.

**Comment by whitead** [comment]
Thanks @mfinzi, will try using latest repo commit.

**Comment by whitead** [comment]
Fixed it, thanks!
