### ISSUE TITLE
Intro Chapter

### ISSUE THREAD

**Issue by whitead** [whitead/dmol-book#43]
Install instructions are messed-up

**Comment by kjappelbaum** [comment]
should probably also add a note that the rdkit wheels are not available for Windows. 

Maybe it is also good to pin some of the versions (maybe at least the major version) and have some CI that installs it and tries to run (some) of the example.

**Comment by whitead** [comment]
Fixed by 4fa0ec4558f692658ad1f26adda30aed0f2e6516
