### ISSUE TITLE
New Chapter: Pre-training

### ISSUE THREAD

**Issue by hgandhi2411** [whitead/dmol-book#53]
* ChemBERT, SMILES-BERT
* Pretraining on graphs and EQNNs

**Comment by whitead** [comment]
See notes too in #99

**Comment by whitead** [comment]
* https://arxiv.org/pdf/2110.00987.pdf
* https://papers.nips.cc/paper/2020/file/3fe230348e9a12c13120749e3f9fa4cd-Paper.pdf
* https://arxiv.org/pdf/2106.04509.pdf
* https://arxiv.org/pdf/2110.07728.pdf

**Comment by whitead** [comment]
Great job @hgandhi2411
