### ISSUE TITLE
ML Intro Chapter Feedback

### ISSUE THREAD

**Issue by whitead** [whitead/dmol-book#54]
- [x]  I’m not sure with the learning problem definitions. RL seems missing and semi/self-supervised are somehow in between.
- [x] Maybe it is good to add a note that if EDA guides the model selection the train/test split needs to happen before EDA to avoid data leakage
- [x] For teaching I would probably use the pandas bracket notation instead of the dot notation as it always works
- [x] Might be interesting to add a note/or exercise why “batch size is usually as a power of 2 (e.g., 16, 128)|
- [x] It might also be interesting to hint at the research about the link between SGD (and the randomness it introduces) and regularization and generalization
- [x] “Here we assume ${y_i}$ is a class variable and try to separate our features into these classes” might not capture that well the case of density-based clustering, similarly “1. We say that clustering is a type of unsupervised learning and that it predicts the labels. What exactly are the predicted labels in clustering? Write down what the predicted labels might look like for a few data points.”
- [x] I feel it cloud be really useful to highlight or hint at some caveats of graph-embedding based clusterings (UMAP/TSNE)
- [x] A ref for the zoo of methods to select k in k-meanshttps://journals.sagepub.com/doi/abs/10.1243/095440605x8298

from @kjappelbaum

**Comment by whitead** [comment]
@kjappelbaum I'm not understanding your comment about density-based clustering. Isn't the result with density-based clusters still a predicted class-label (or distribution of class-labels?).

**Comment by kjappelbaum** [comment]
I think i found the explanation of clustering to be (maybe) too similar to a classification tasks (where your learning goal is to separate into $k$ classes that you already know such that you can provide proper supervision). 

In particular for density based clustering however, you do not have a clue about what $k$ is. Which makes it for me quite distinct from classification (and as you mentioned somewhere --- i think i also saw it in one of your tweets --- much more fuzzy to evaluate).  From this point of view, 

> Here we assume  ${y_i}$ is a class variable and try to separate our features into these classes 

is maybe a bit hard to interpret for density based clustering where the low density regions might all just be outliers or rare classes

**Comment by whitead** [comment]
But fundamentally in density based-clustering, your y_i is still a class variable (perhaps an integer though) right? I believe DBSCAN for example outputs class integers and -1 for "outlier" or uncategorized. Do you have an example in mind where clustering doesn't result in class labels? Or, do you have a qualification/expansion on the definition you're thinking of?

**Comment by kjappelbaum** [comment]
I think my comment was that the way it was written it sounded to me (non-native speaker :D) as the y_i are known and you want to use clustering to assign observations to these known classes y_i. (This is usually true, but a bit more complicated when you go for example, to hierarchical clustering or some mixture models. )

So the way I thought about clustering (but this is maybe too naive) is that 

> Clustering attempts to partition observations into "clusters" such that observations within clusters are more similar to each other than to elements in different clusters. 

But i guess what i'm doing now is hairsplitting ....

**Comment by whitead** [comment]
@kjappelbaum No it's good feedback. I will revise to be clearer, just trying to understand the subtlety of what you're getting at with density clustering.
