### ISSUE TITLE
add spellcheck and link check CI? 

### ISSUE THREAD

**Issue by kjappelbaum** [whitead/dmol-book#63]
similar to https://github.com/cheminfo/eln-docs/blob/main/.github/workflows/spellcheck.yml and https://github.com/cheminfo/eln-docs/blob/main/.github/workflows/check_links.yml.

if you think it is useful, i can make the PR. 

the spellcheck CI might be annoying at first, when you do not yet have a good [whitelist](https://github.com/cheminfo/eln-docs/blob/main/wordlist.txt) but might be pretty useful in the long run

**Comment by whitead** [comment]
Great suggestion. I'm going to work on CI soon now that PRs are picking-up. Will include these.

**Comment by whitead** [comment]
Fixed by #67
