### ISSUE TITLE
Chapter 10: Input Data and Equivariances

### ISSUE THREAD

**Issue by juliawestermayr** [whitead/dmol-book#71]
Chapter 10 gives a very nice overview of different representations for molecules and shows how to incoporate variances. I really like the jupyter notebooks and the examples that nicely illustrate the concepts. 

* The examples (chapter 10.3) give a good overview. At this point, I think it would be nice to mention which models are also suitable/feasible for materials, especially when periodic boundary conditions are needed. How can this be incorporated? A few sentenes would be very helpful.
* Regarding typos, I am not sure how to address these, so I will do it here as well: I suggest to place the last sentence in the introduction ("Simularly, our output energy should not be sensitive to a rotation of the molecular coordinates.") to the end of the previous paragraph. Right now it reads: Translation --> permutation --> rotation. I think it is much easier to follow if rotation and translation come together and are not split by the concept of permutation variance.
* There is a typo in the last paragraph: "Our model changes if we re-order _or_ inputs" --> "Our model changes if we re-order _our_ inputs"
* Chapter 10.1: I believe that it is very difficult for people who are not familiar with these concepts to follow. It would be extremely helpful to just show a simple example, e.g. H2O. One could simply show the vector of approximate partial charges for H2O in 2 ways: OHH = (-1,0.5,0.5) and HOH = (0.5,-1,0.5). The rest is very clear.
* Chapter 10.3.8: "... they can be an input layer _for if_ translational... " does not sound correct to me.
* Chapter 10.3.11: "... is _a_ unsolved problem ..." --> "... is _an_ unsolved problem ..."
* Chapter 10.3.11: Could you please give examples of common fingerprints used or maybe point to a reference?
* Chapter 10.4.: Punctuation in the first sentence is missing.
* Chapter 10.7.3: After the first sentence, can you still add some of the early references?

**Comment by whitead** [comment]
Hi @juliawestermayr  Thanks for taking the time to write out these proposed changes! It's very helpful and I'm glad to hear you find the chapter useful. I'll follow-up when I have time on these.
