### ISSUE TITLE
Chapter 13: Equivariant Neural Networks

### ISSUE THREAD

**Issue by juliawestermayr** [whitead/dmol-book#73]
Chapter 13 gives a comprehensive overview of the mathematical background and the concept of equivariant neural networks with some great examples. Although I have read about this topic before, I was not completely familiar with it, but chose it, because I wanted to learn about it. I have to say: Although it was not always easy to read, I learned a lot! Thank you for your efforts in putting this together and also for providing the great resources to look things up. I especially liked the links to the youtube videos.
That said, I think I cannot judge whether the equations are correct or not, but at least I can give feedback on typos and code that did not work:
* I read about the Haar measure in the chapter. It was the first time I heard about it so it would be helpful if there could be a sentence explaining what it is when it is first mentioned in the text.
* The installation that we have to carry out in the beginning on google colab is incomplete. For chapter 13.10 we also need haiku, so this needs to be installed in the beginning.
* 13.1, first paragraph: "... on many of the tasks the're desin_ed_ for...'
* Please check equation 13.1 - is it really GxX --> X ?  If so, could you please add a sentence to explain this a little bit more as the next sentence after the equation says that a point is transformed to a new point, but the equation has the same X?
* 13.3.2.: Paragraph starting with "... As you can see from the ayley table,..."- The next sentence has a typo: "_hance_" --> "_hence_"
* 13.3.2.: Paragraph starting with "Combining these two groups..." --> typo in the phrase: "... so this _make_ sense." --> "... so this _makes_ sense."
* 13.3.2.: Info box "Semidirect Product": typo "_subrgoup_" --> "_subgroup_"
* 13.8.: The first code does not work. It cannot find the image "quadimg.png". Consequently, the rest of the code does not work too.
* 13.9.: Second-last paragrph starting with "Remember the way a group affects...". This sentence is missing a bracket. 
* 13.9.1., shortly after equation 13.14: "The Haar measure for SO(3) _in with_ our group ..." does not sound correct to me.
* 13.9.1.: next paragrph, middle sentence: "the integral with the irreducible representation in _Equation X_." Please refer to the correct equation.
* 13.10.1.: Sentence before equation 13.17: "_like_ like" --> "_look_ like"
* 13.10.2.: The second cell reports an error in the input dimension. Consequently also the rest of the code does not work.

**Comment by whitead** [comment]
@juliawestermayr I've addressed all these questions, but I'm not sure about 13.10.2 error. The book is generated by executing the code, so all the code must be error free for the textbook to work. Could you double-check if you have a chance and tell me what versions of each package you have?

You can see feedback from your two issues in #78
