### ISSUE TITLE
Feedback: Tensors and Shapes

### ISSUE THREAD

**Issue by cabergh** [whitead/dmol-book#81]
- The matrix multiplication example might be clearer with “The matric product of 2 tensors each with rank 2”?

- In Why Tensors?: spelling mistake “...how shape affects them is they key…” -> “... is the key…”

- Second sentence in 1.2 Tensor Operations: question mark missing?

- In newaxis: why is there an angry face after “unsqueeze”? There is also a . missing. Perhaps it would be better to say “You can also use reshape instead of newaxis” instead of “ignore”? I’m also not able to click the links in this side comment.

- In 1.4 Modify Rank: I don’t understand why np.squeeze would be more general if it only removes axes with dimension 1, while slicing can remove ranks with any dimension?

- In 1.4 Modify Rank: in the second example, squeeze is misspelled (squeese)

- In 1.4.2. Rank Slicing: I think the first sentences could be formulated a bit more nicely. E.g. “I hope you’re now familiar with slicing in numpy/Python, but if you feel like you need a refresher I recommend this Python tutorial or numpy tutorial.

- In 1.6 Chapter Summary: “...modifies shapes of tensors make them compatible with operations.” ->  “...to make them compatible…”. What does it mean to make tensors compatible with operations? You mean “modifies shapes of tensors to enable valid tensor operations”?

- In 1.6 Chapter Summary: spelling mistake in the last bullet point: “ranked” -> “rank”. I also think the sentence could be improved, e.g. “The rank of a tensor can be modified by newaxis, reshape or squeeze. However, these methods are not the standard among the various numeric Python libraries”. I’m not completely sure what is meant by the last sentence. What is meant by standard in this case? Not commonly used or not implemented? Then, what is the standard? Usually, people want to use what’s most standard?

**Comment by awoonor** [comment]
Very thorough feedback by @cabergh and Great book @whitead! 
I really enjoyed reading the few chapters I could read and I think this is a great resource for students and learners alike.
I echo most of @cabergh comments here and came across a few typos which have already been addressed. 

In the Reduction Operations section in Chapter 1, there is a typo: "You can specify a tuple of axes to removed", should read "You can specify a tuple of axes to **remove**"

**Comment by whitead** [comment]
Thanks, fixed in #103
