### ISSUE TITLE
Feedback: Classification

### ISSUE THREAD

**Issue by cabergh** [whitead/dmol-book#84]
- In 4. Classification: “…distance from decision boundary…” -> “...from a/the decision…”

- In 4. Classification: “...can be applied to this problem.” -> “...can be applied to classification.” would be clearer.

- In 4. Classification: “The classic application of classification in structure-activity relationship in drug discovery, where we want to predict if a molecule will be active (positive class) as a function of structure. That dates back to the 1970s.” -> “The classic application of classification in structure-activity relationship in drug discovery, where we want to predict if a molecule will be active (positive class) as a function of structure, dates back to the 1970s.”

- In 4. Classification: “Classification is widely used now in materials and chemistry. Many molecular design problems can be formulated as classification.” There are many short sentences in this part, and I believe some could be merged. E.g. “Algorithms for classification problems are widely used now in materials and chemistry, since many molecular design problems can be formulated as a classification task.”

- In 4.4.1. Linear Perceptron: The discussion regarding the training of the perceptron is interesting, but I feel like it’s cut-off in the end with “Rather than teach and discuss the special perceptron training procedure, we’ll move to a more modern related classifier called a softmax binary classifier.” I think something more could be said about the difference between the perceptron and softmax classifier to better motivate the change of methods.

- In 4.5.1. Error Types: “Now are we still predicting positives?” -> “Now, are we…”

- In 4.5.1. Error Types: “...our model is actually capable of predicting molecules will pass FDA clinical trials...” -> “...molecules that will pass…”

- In 4.5.1. Error Types: “The x-axis of ROC curve is false positive rate and y-axis is true positive rate.” -> “The x-axis of the ROC curve represents the false positive rate, while the y-axis represents the true positive rate.”

- In 4.5.1. Error Types: “Each point on the plot is our model with a different threshold.” -> “Each point on the plot represents the model but with a different threshold value.”?

- In 4.5.1. Error Types: “How do we choose which thresholds to use? Well it’s just the number of unique class probabilities we saw. We do need to add two extremes: all positive and all negative. So for example, our alt model will only have one point on this curve. Let’s make one and discuss what we’re seeing.” I find this paragraph a bit difficult to follow, partly due to many short sentences. What is meant by “all positive and all negative”? Linguistically, I think these refer to the class probabilities, but one of those can’t be negative?

- In 4.6 Class Imbalance: “...is that we have very few negative example – molecules which failed FDA clinical trials.” -> “...few negative examples, i.e. molecules that failed FDA clinical trials”.

- In 4.6 Class Imbalance: “The first answer is: is this a problem at all?” I’m not sure this is an answer, it looks like a question to me.

- In 4.6 Class Imbalance: “If you’re testing data…” -> “...your testing data…”.

- In 4.6 Class Imbalance: “...false positive are rarer and also more important in reality.” -> “...false positives are…”. Also, what is meant by more important in this case? More important to detect?

- In 4.6 Class Imbalance: A name is spelled “Bryrd” in the first sentence, “Bryd” in the second and “Byrd” in the reference. I believe it should be “Byrd”.

**Comment by awoonor** [comment]
Paragraph 2 of Classification introduction: "The goal of classification to find a function that ..." should read "The goal of classification **is** to find a function that ...".

**Comment by whitead** [comment]
Fixed by ac520bf3d48a8d050e0697189e3a05ee2cc2c0f2
