### ISSUE TITLE
Feedback: Kernel Learning

### ISSUE THREAD

**Issue by cabergh** [whitead/dmol-book#85]
- In 5. Kernel Learning: “Kernel learning is a widely-used approach for learning potential energy functions and force fields in molecular modeling” . missing.

- In 5. Kernel Learning: “...you could use a binary molecular dynamics simulation to compute the kernel between two molecules.” Here, it would be nice with a reference.

- In 5. Kernel Learning: “This makes it so that our kernel output magnitude is independent of the number of dimensions…” -> “This makes our kernel output magnitude independent of the number of dimensions.”

- In 5.4 Training: in the second cell the term “epoch” is used, but I believe it was never introduced. It would be nice with a comment about the meaning of this term.

- In 5.4 Training: “I have not done many epochs.” Again, I believe this term wasn’t introduced yet.

- In 5.4 Training: The notebook cells contain some commands for plotting, but no plots are displayed. It would be nice to see the plots for readers who don’t want to run the code.

- In 5.6 Training Curves: Again, no plots are displayed.

- In 5.8 Chapter Summary: “A kernel function takes two arguments and outputs a scalar. It has three properties: positive, symmetric, and point-separating.” It would be good to clarify that the kernel function has these properties, not the scalar.

**Comment by whitead** [comment]
Fixed by 3230749e298265be826be65f4e3c58ce6f35f639
