### ISSUE TITLE
Feedback: Introduction to Deep Learning

### ISSUE THREAD

**Issue by cabergh** [whitead/dmol-book#86]
- In 6. Introduction: “These notes are mostly about deep learning, thus the name of the book.” I think this could be reformulated, e.g. “This book will be focused on deep learning, hence the name of the book”. 

- In 6. Introduction: “chemistry specific” -> “chemistry-specific”

- In 6.1 Neural Networks: “...is a differentiable function we design composed of layers,...”. I think this would be clearer as “...is a differentiable function composed of layers,...”

- In 6.1 Neural Networks: “problem dependent” -> “problem-dependent”

- In 6.1.1 Universal Approximation Theorem: “...with ReLU activation functions with infinitely wide layers (infinite hidden dimension) []”. Is there a reference missing here?

- In 6.1.2 Frameworks: “We will move to a bit of a more abstract software framework than JAX for some examples.” -> “We will move to a slightly more abstract software framework compared to JAX for some examples.”

- In 6.4 Neural Network: This subtitle is basically the same as for 6.1. Could it be more specific?

- In 6.4 Neural Network: “We’ll choose our activation, , to be tanh and the output dimension of the hidden-layer to be 32.” Here, I think it would be nice with a brief motivation to these choices.

- In 6.4 Neural Network: “You can read more about this API here” -> “...about the Keras API here.”

**Comment by whitead** [comment]
Fixed by 94efcd0
