### ISSUE TITLE
Feedback: Graph Neural Networks

### ISSUE THREAD

**Issue by cabergh** [whitead/dmol-book#88]
- In 8.1 Representing a Graph: “Figure Fig. 8.1.” Figure is repeated.

- In 8.4: “One of the first popular GNNs is the Kipf & Welling graph convolutional network (GCN)” -> “One of the first popular GNNs was the…”?

- In 8.4: “So you can stack multiple layers.” -> “Instead, you can stack…”

- In 8.4: Why is the caption above the graphics in Fig 8.3?

- In 8.4: It would be nice if there could be an iteration number in the animation, or something indicating the start, especially since it repeats one time.

- In 8.5: “Then we have to pass it…” -> “Then, we have to pass…”

- In 8.8: “Typically you see sum or mean in...” -> “Typically, you see sums or means…” 

- In 8.8: “Typically you see sum or mean in GNNs, but you can be quite sophisticated like in Graph Isomorphism Networks”. I find this sentence a bit hard to understand. First, should it really be the person who’s sophisticated here? How is it sophisticated compared to sums or means?

- In 8.9: “...a reduction over nodes to get graph feature and then dense layers to get predicted graph label from graph feature.” Perhaps “...to get graph features and then dense layers to get predicted graph labels from graph features”?

- In 8.9: “DeepDets” -> “DeepSets”

- In 8.10: “...to build-up...” -> “...to build up...”

- In 8.10: “Any kind of per-molecule quantity like energy should…” -> “Any kind of per-molecule quantity, like energy, should…”

- In 8.10: “...which note is sending…” -> “...node…”

- In 8.10.1: “The other functions are not used so that is the complete set.” It’s a bit unclear what “that” refers to.

- In 8.11: “...the edges are distance between the atoms…” -> “...the edges represent distances between the atoms…”

- In 8.11: “edge updating” -> “edge-updating”

- In 8.12: “These can all be represented in the Battaglia equations, but you should be aware of these names.” -> “...so you should be aware…”?

- In 8.12: “agreed upon” -> “agreed-upon”

**Comment by whitead** [comment]
Fixed by a1a7626
