### ISSUE TITLE
[WIP] Flow feedback

### ISSUE THREAD

**Issue by kjappelbaum** [whitead/dmol-book#93]
- [x] I perhaps would give a really fancy example: For instance, the Boltzmann sampler science paper (if coupled to mol sim classes this is also a nice example to review reweighing). [The highlight piece from Tuckermann](https://www.science.org/lookup/doi/10.1126/science.aay2568) is quite nice. They (Noe group) also have a [Python package](https://github.com/noegroup/bgflow) that helps.

**Comment by whitead** [comment]
Have taken a close look at it. It looks a bit beyond the scope of this chapter -- but getting a more authentic example for this chapter is on my todo list.
