### ISSUE TITLE
new chapter (?) TDA 

### ISSUE THREAD

**Issue by kjappelbaum** [whitead/dmol-book#98]
again, i was too diffuse today. 

one thing that is interesting, especially for porous materials. Is topological data analysis. You could then also apply DL techniques, e.g., on persistence images 

not sure if this is better than using something like PointNet (might be worth a research project to systematically compare them)

**Comment by whitead** [comment]
Finally got some time to learn more about TDA. Although there is some early work (Wassterstein), I don't think the connection is strong enough to warrant adding. Will keep my eye on it though!
